call getApi function when clicking button in collapsable
Codubee/StockPickerMW10-11-Front pull request #16
Opened 2021-08-17 03:05 UTC by BrandonAlexanderLopez

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
The getAPI function is called when the "click me" button is pressed on the match page.

* **What is the current behavior?What does the code do before you made the new changes?** 
Previously the click me button had no function. 
Now, the click me button displays the matches from the API.

* **What is the new behavior?**
The click me button displays the matches from the API.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
Nothing breaks

* **Other information**:
![image](https://user-images.githubusercontent.com/54815073/129657321-32414b67-415d-44ce-996a-0b7f2ef0e1dc.png)
![image](https://user-images.githubusercontent.com/54815073/129657384-c335bf89-3a74-475f-bfee-9559d11a15c5.png)

2021-08-18 15:31 UTC, Sakamoto448 reviewed
looks good to me, nice job Brandon!

2021-08-18 15:31 UTC, Sakamoto448 approved these changes, later dismissed

2021-08-18 20:49 UTC, Codubee requested changes
Theres no code to review here.

2021-08-19 04:58 UTC, Codubee approved these changes
LGTM!

2021-08-19 04:58 UTC, merged