Mf 6 navbar
Codubee/StockPickerMW10-11-Front pull request #2
Opened 2021-07-14 15:27 UTC by BrandonAlexanderLopez

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)

* **What is the current behavior?What does the code do before you made the new changes?** 

* **What is the new behavior?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)

* **Other information**:

2021-07-14 15:34 UTC, BrandonAlexanderLopez commented
_What kind of change does this PR introduce? (Bug fix, new feature...)_
**The navbar has been added to the application**
_What is the current behavior? What does the code do before you made the new changes?_
**You may now select options in the menu. 
Some pages aren't finished yet meaning selecting that option in the menu returns no function.** 
_What is the new behavior?_
**The new behavior of our app is that it allows users to make selections in the newly available navbar.**
_Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR? Run a new command?)_
**As is nothing is BROKEN, but the navbar still has some work to be done. It is not fully functional yet, however there is currently no breaks**

2021-07-14 17:17 UTC, Sakamoto448 approved these changes, later dismissed
Tried it out, Nothing breaks and all components work. Looks good to me, nice job!

2021-07-14 20:49 UTC, Codubee commented on src/components/Navigation.js
> +              </UncontrolledDropdown>
I think a lot of these links are not needed for now. What do you think about removing them?

2021-07-14 20:49 UTC, Codubee requested changes
Left a comment for discussion

2021-07-14 20:55 UTC, BrandonAlexanderLopez commented on src/components/Navigation.js
> +              </UncontrolledDropdown>
Agreed, will do.

2021-07-19 15:33 UTC, Codubee approved these changes
LGTM!

2021-07-19 15:33 UTC, merged