added Tools component
Codubee/StockPickerMW10-11-Front pull request #3
Opened 2021-07-19 15:30 UTC by Sakamoto448

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Added Tools Component to the application.

* **What is the current behavior?* What does the code do before you made the new changes?** 
There was no existing text other than Hello World

* **What is the new behavior?**
You may now see, what a list of tools the team will be using for the project.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
Everything seems to be in place and nothing is breaking, however the list is quite bland and will still need some work aesthetically.

* **Other information**:

2021-07-19 15:40 UTC, Codubee requested changes
Left a comment for discussion

2021-07-19 15:40 UTC, Codubee commented on src/components/Tools.js
> +        <h1> Jira </h1>
Typically h1 tags are reserved for titles of pages. What do you think about using an [html list ](https://www.w3schools.com/html/html_lists.asp)or h2,h3,h4, or h6 tag instead?

Also, you may have asked a question about this before but can we add a title on top of this explaining what the section is for.

2021-07-19 15:42 UTC, BrandonAlexanderLopez commented on src/components/Tools.js
> +        <h1> Jira </h1>
I agree with Miguel, shall I review after these changes?

2021-07-27 20:31 UTC, Miguel-S117 reviewed
Looks great and works! What do you think about moving the ExplanationPage feature above the Tools feature so the ExplanationPage will be shown at the top of the site and the list of tools below it?

2021-07-28 03:39 UTC, BrandonAlexanderLopez approved these changes

2021-07-28 03:51 UTC, BrandonAlexanderLopez approved these changes, later dismissed

2021-07-28 14:49 UTC, Miguel-S117 approved these changes, later dismissed

2021-07-28 15:06 UTC, BrandonAlexanderLopez approved these changes, later dismissed

2021-07-28 15:17 UTC, Codubee approved these changes
LGTM!

2021-07-28 15:17 UTC, merged