Added Matches Component, (Values hard-coded, no use of API's yet)
Codubee/StockPickerMW10-11-Front pull request #7
Opened 2021-07-28 03:30 UTC by BrandonAlexanderLopez

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
The matches component has been added.
It displays the company name, symbol, and price.

* **What is the current behavior?What does the code do before you made the new changes?** 
Currently the companies and stocks are hard-coded meaning the values are static.
Once we incorporate the API's and add more functionality to our app then the matches will be dynamic

* **What is the new behavior?**
The matches component has been added.
It displays the company name, symbol, and price.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)* 
* NO, nothing breaks

* **Other information**:
CURRENT OUTPUT:
![image](https://user-images.githubusercontent.com/54815073/127259190-fb618000-3c76-4242-b92d-5e62a1886cda.png)

2021-07-28 06:39 UTC, Sakamoto448 submitted a review, later dismissed
Looks good to me. Ran the code and saw everything from the picture that you had. Nothing crashed and all static values were present. Nice Job!

2021-07-28 15:37 UTC, Codubee commented on src/components/Matches.js
> +const Matches = (props) => {
I see that the components you create start with the const keyword. Can you change these into functional components instead?

2021-07-28 15:37 UTC, Codubee requested changes
Left some comments

2021-08-03 17:56 UTC, Codubee requested changes
Great first attempt here Brandon, but can you display a javascript array of objects here instead of hard coded values. I included some documentation in the ticket description if youd like some help.

2021-08-11 00:44 UTC, BrandonAlexanderLopez reviewed
That has been reviewed and changed.

2021-08-11 01:18 UTC, BrandonAlexanderLopez commented
![image](https://user-images.githubusercontent.com/54815073/128955038-bbe8a6e9-f942-4334-81b9-be3f96f1f395.png)
The matches are now an array of objects however the output doesn't look as nice as if it was in the form of a table.

2021-08-11 15:24 UTC, Codubee approved these changes
LGTM!

2021-08-11 15:24 UTC, merged